# Generated by Django 4.0.2 on 2022-02-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('resume_html', models.TextField(blank=True)),
                ('resume_pdf', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MyObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, upload_to='')),
                ('video_1', models.ImageField(blank=True, upload_to='')),
                ('video_2', models.ImageField(blank=True, upload_to='')),
                ('video_3', models.ImageField(blank=True, upload_to='')),
                ('video_4', models.ImageField(blank=True, upload_to='')),
                ('video_5', models.ImageField(blank=True, upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.persons')),
            ],
        ),
    ]
